### ISSUE TITLE
Move to DCF Org?

### ISSUE THREAD

**Issue by carltongibson** [django-crispy-forms/crispy-test-project#2]
Fancy moving this to the org? 

(As part of my grand plans... 🙂 https://github.com/django-crispy-forms/django-crispy-forms/projects)

**Comment by zoidyzoidzoid** [comment]
Sounds like a great idea. Happily.

**Comment by zoidyzoidzoid** [comment]
I am having trouble commenting anywhere on the project management stuff or adding cards.

**Comment by carltongibson** [comment]
Hmm. Let me have a look...

**Comment by zoidyzoidzoid** [comment]
You can convert that existing card to an issue, and then I'll comment there.

**Comment by zoidyzoidzoid** [comment]
Transferred. :+1:

**Comment by carltongibson** [comment]
I found the right button! 😀 (You should now have all access to crispy_forms.)
